naming:
  active: true
  FunctionNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/androidUnitTest/**', '**/androidInstrumentedTest/**', '**/jsTest/**', '**/iosTest/**']
    functionPattern: '[a-zA-z][a-zA-Z0-9]*'
style:
  active: true
  NewLineAtEndOfFile:
    active: false