
name: Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        description: "Manual debug build description"
        default: "Release notes"

jobs:
  build:
    name: "Build and Distribute App"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Run assembleDebug
        run: ./gradlew assembleDebug

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIRE_BASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: ${{ inputs.release_notes }}
